version: "3.7"

services:
  cl-frontend:
    container_name: cl-frontend
    environment:
      API_ENDPOINT: 'https://localhost'
    build:
      context: ./
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
